/* Shark Automotive — types matching the design prototypes' mock shapes.
   Generated by hand to mirror schema.sql; regenerate with
   `supabase gen types typescript` once the schema is applied. */

export type UserRole       = 'admin' | 'staff' | 'customer';
export type VehicleStatus  = 'available' | 'reserved' | 'sold' | 'draft';
export type FuelType       = 'gasolina' | 'diesel' | 'hibrido' | 'eletrico';
export type GearboxType    = 'manual' | 'automatica';
export type OperationType  = 'encomenda' | 'comprador';
export type OperationState = 'active' | 'delivered' | 'cancelled';
export type PaymentStatus  = 'scheduled' | 'pending' | 'paid' | 'failed' | 'refunded';
export type LeadStatus     = 'novo' | 'contactado' | 'qualificado' | 'negociacao' | 'convertido' | 'perdido';
export type LeadSource     = 'importacao' | 'contacto' | 'dossier' | 'parceiros';
export type DocType        = 'orcamento' | 'proposta' | 'declaracao' | 'ficha' | 'factura' | 'outro';
export type DocStatus      = 'rascunho' | 'emitido' | 'enviado' | 'aceite' | 'recusado';
export type DocVisibility  = 'interno' | 'cliente';
export type ContentStatus  = 'publicado' | 'pendente';

/** Chip tones used by the design system. See README → Design tokens. */
export type ChipTone = 'verde' | 'ambar' | 'azul' | 'vermelho' | 'neutro';

export interface Profile {
  id: string;
  role: UserRole;
  full_name: string | null;
  phone: string | null;
  nif: string | null;
  address: string | null;
  created_at: string;
}

export interface Vehicle {
  id: string;
  make: string;
  model: string;
  variant: string | null;
  year: number;
  mileage_km: number;
  price_eur: number;
  monthly_from_eur: number | null;
  fuel: FuelType | null;
  gearbox: GearboxType | null;
  power_cv: number | null;
  displacement_cc: number | null;
  co2_gkm: number | null;
  doors: number | null;
  seats: number | null;
  colour: string | null;
  interior: string | null;
  vin: string | null;
  plate: string | null;
  foreign_plate: string | null;
  first_reg_date: string | null;
  origin_country: string | null;
  origin_source: string | null;
  status: VehicleStatus;
  /** Drives visibility on the public site (admin → Visibilidade no site). */
  published: boolean;
  featured: boolean;
  protocol_passed: number;
  protocol_total: number;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface VehiclePhoto {
  id: string;
  vehicle_id: string;
  storage_path: string;
  label: string | null;
  sort_order: number;
}

export interface Lead {
  id: string;
  name: string;
  email: string | null;
  phone: string | null;
  source: LeadSource;
  status: LeadStatus;
  interest: string | null;
  budget_eur: number | null;
  vehicle_id: string | null;
  message: string | null;
  operation_id: string | null;
  created_at: string;
}

export interface Operation {
  id: string;
  ref: string;
  customer_id: string | null;
  lead_id: string | null;
  type: OperationType;
  state: OperationState;
  vehicle_id: string | null;
  vehicle_label: string | null;
  total_eur: number;
  /** 1..8 — see OPERATION_STEPS */
  current_step: number;
  eta_weeks_min: number | null;
  eta_weeks_max: number | null;
  created_at: string;
  updated_at: string;
}

export interface OperationStep {
  operation_id: string;
  step: number;
  completed_at: string | null;
  note: string | null;
}

export interface OperationCost {
  id: string;
  operation_id: string;
  label: string;
  detail: string | null;
  amount_eur: number;
  sort_order: number;
}

export interface Payment {
  id: string;
  operation_id: string;
  description: string;
  amount_eur: number;
  status: PaymentStatus;
  method: string | null;
  due_date: string | null;
  paid_at: string | null;
  stripe_link_url: string | null;
  stripe_session_id: string | null;
  sort_order: number;
}

export interface SharkDocument {
  id: string;
  ref: string | null;
  type: DocType;
  status: DocStatus;
  visibility: DocVisibility;
  operation_id: string | null;
  vehicle_id: string | null;
  customer_id: string | null;
  title: string | null;
  amount_eur: number | null;
  payload: Record<string, unknown> | null;
  storage_path: string | null;
  valid_until: string | null;
  issued_at: string | null;
  created_at: string;
}

export interface OperationMessage {
  id: string;
  operation_id: string;
  author_id: string | null;
  from_staff: boolean;
  body: string;
  read_at: string | null;
  created_at: string;
}

export interface SiteMessage {
  id: string;
  name: string;
  email: string | null;
  phone: string | null;
  source: LeadSource;
  body: string;
  lead_id: string | null;
  handled_at: string | null;
  created_at: string;
}

export interface SiteContent {
  id: string;
  page: string;
  block: string;
  status: ContentStatus;
  content: Record<string, unknown>;
  updated_at: string;
}

export interface Settings {
  id: 1;
  company_name: string | null;
  legal_name: string | null;
  nipc: string | null;
  address: string | null;
  phone: string | null;
  email: string | null;
  iban: string | null;
  cost_transport_eur: number;
  cost_registration_eur: number;
  commission_fixed_eur: number;
  service_fee_order_eur: number;
  warranty_6m_eur: number;
}

/** The 8 pipeline steps, in order. Mirrors operation_step_defs. */
export const OPERATION_STEPS = [
  { step: 1, title: 'Pedido qualificado',  note: 'Briefing e orçamento aprovados pelo cliente.' },
  { step: 2, title: 'Briefing recebido',   note: 'Marca, modelo, orçamento e extras confirmados.' },
  { step: 3, title: 'Viatura localizada',  note: 'Opções apresentadas com conta fechada.' },
  { step: 4, title: 'Inspecção na origem', note: 'Relatório técnico e fotografias na rampa.' },
  { step: 5, title: 'Contrato assinado',   note: 'Sinal liquidado e viatura reservada.' },
  { step: 6, title: 'Transporte',          note: 'Porta-carros coberto, com rastreamento.' },
  { step: 7, title: 'Legalização',         note: 'ISV, matrícula nacional e registo.' },
  { step: 8, title: 'Entregue',            note: 'Entrega ao domicílio e garantia activa.' },
] as const;

/** The 6 protocol stages summing to 150 points. Mirrors protocol_stages. */
export const PROTOCOL_STAGES = [
  { id: 1, name: 'Verificação documental', points: 12 },
  { id: 2, name: 'Inspecção técnica',      points: 46 },
  { id: 3, name: 'Registo fotográfico',    points: 38 },
  { id: 4, name: 'Transporte',             points: 18 },
  { id: 5, name: 'Legalização',            points: 22 },
  { id: 6, name: 'Garantia',               points: 14 },
] as const;
